import streamlit as st
import pandas as pd
import random
import requests
import os
from datetime import datetime
from fpdf import FPDF
import base64

# --- CONFIGURACIÓN ---
st.set_page_config(page_title="TalentPro Global", layout="wide", page_icon="🌎")

st.markdown("""
    <style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    .stMetric {background-color: #f8f9fa; border: 1px solid #dee2e6; padding: 10px; border-radius: 5px;}
    /* Botón personalizado */
    div.stButton > button:first-child {
        background-color: #003366;
        color: white;
        border-radius: 8px;
    }
    </style>
""", unsafe_allow_html=True)

# ==============================================================================
# 1. GESTIÓN DE LOGO (Descarga automática)
# ==============================================================================
LOGO_URL = "https://bukwebapp-enterprise-chile.s3.amazonaws.com/talentpro/generals/logo_login/logo_login.jpg"
LOGO_PATH = "logo_talentpro.jpg"

@st.cache_resource
def descargar_logo():
    if not os.path.exists(LOGO_PATH):
        try:
            response = requests.get(LOGO_URL)
            if response.status_code == 200:
                with open(LOGO_PATH, 'wb') as f:
                    f.write(response.content)
        except:
            pass # Si falla, el PDF se generará sin logo sin romperse

descargar_logo()

# ==============================================================================
# 2. TRADUCCIONES Y ENTIDADES
# ==============================================================================
TEXTOS = {
    "ES": {
        "title": "Cotizador TalentPro", "client": "Información del Cliente", "items": "Selección de Servicios",
        "add": "Agregar", "desc": "Descripción del Servicio / Producto", "qty": "Cant.", "unit": "Precio Unitario", "total": "Total",
        "subtotal": "Subtotal Neto", "fee": "Fee de Administración (10%)", "tax": "Impuestos", "discount": "Descuento Especial",
        "grand_total": "TOTAL A PAGAR", "download": "Descargar Propuesta (PDF)", "invoice_to": "Preparado para:",
        "quote": "COTIZACIÓN", "date": "Fecha de Emisión", "validity": "Validez de la oferta: 30 días",
        "save": "Generar Cotización", "generated": "Documento generado digitalmente por TalentPro System"
    },
    "EN": {
        "title": "TalentPro Quote Tool", "client": "Client Information", "items": "Service Selection",
        "add": "Add Item", "desc": "Service / Product Description", "qty": "Qty", "unit": "Unit Price", "total": "Total",
        "subtotal": "Net Subtotal", "fee": "Admin Fee (10%)", "tax": "Taxes", "discount": "Special Discount",
        "grand_total": "GRAND TOTAL", "download": "Download Proposal (PDF)", "invoice_to": "Prepared for:",
        "quote": "QUOTATION", "date": "Issue Date", "validity": "Offer validity: 30 days",
        "save": "Generate Quote", "generated": "Digitally generated by TalentPro System"
    },
    "PT": {
        "title": "Cotação TalentPro", "client": "Informações do Cliente", "items": "Seleção de Serviços",
        "add": "Adicionar", "desc": "Descrição do Serviço / Produto", "qty": "Qtd", "unit": "Preço Unitário", "total": "Total",
        "subtotal": "Subtotal Líquido", "fee": "Taxa Administrativa (10%)", "tax": "Impostos", "discount": "Desconto Especial",
        "grand_total": "TOTAL A PAGAR", "download": "Baixar Proposta (PDF)", "invoice_to": "Preparado para:",
        "quote": "COTAÇÃO", "date": "Data de Emissão", "validity": "Validade da oferta: 30 dias",
        "save": "Gerar Cotação", "generated": "Gerado digitalmente pelo TalentPro System"
    }
}

EMPRESAS = {
    "Brasil": {
        "Nombre": "TalentPRO Brasil Consutoria Ltda.",
        "ID": "CNPJ: 49.704.046/0001-80",
        "Dir": "Av. Marcos Penteado de Ulhoa Rodriguez 939, Andar 8, Tamboré",
        "Giro": "Consultoria em gestão empresarial"
    },
    "Peru": {
        "Nombre": "TALENTPRO SOCIEDAD ANÓNIMA CERRADA",
        "ID": "DNI 25489763",
        "Dir": "AVENIDA EL DERBY 254, SANTIAGO DE SURCO, LIMA, PERÚ",
        "Giro": "Servicios de apoyo a las empresas"
    },
    "Chile_Pruebas": {
        "Nombre": "TALENT PRO SPA",
        "ID": "RUT: 76.743.976-8",
        "Dir": "Juan de Valiente 3630, oficina 501, Vitacura, Santiago, Chile",
        "Giro": "Servicios de Reclutamiento y Selección"
    },
    "Chile_Servicios": {
        "Nombre": "TALENTPRO SERVICIOS PROFESIONALES LTDA.",
        "ID": "RUT: 77.704.757-4",
        "Dir": "Juan de Valiente 3630, oficina 501, Vitacura, Santiago, Chile",
        "Giro": "Asesoría en Recursos Humanos"
    },
    "Latam": {
        "Nombre": "TALENTPRO LATAM, S.A.",
        "ID": "RUC: 155723672-2-2022 DV 27",
        "Dir": "CALLE 50, PH GLOBAL PLAZA, OFICINA 6D, BELLA VISTA, PANAMÁ",
        "Giro": "Talent Acquisition Services"
    }
}

# --- 2. CARGA DE DATOS (EXCEL) ---
@st.cache_data(ttl=60)
def cargar_datos():
    try:
        xls = pd.ExcelFile('precios.xlsx')
        df_p_usd = pd.read_excel(xls, 'Pruebas Int')
        df_s_usd = pd.read_excel(xls, 'Servicios Int')
        df_config = pd.read_excel(xls, 'Config')
        df_p_cl = pd.read_excel(xls, 'Pruebas_CL') if 'Pruebas_CL' in xls.sheet_names else pd.DataFrame()
        df_s_cl = pd.read_excel(xls, 'Servicios_CL') if 'Servicios_CL' in xls.sheet_names else pd.DataFrame()
        df_p_br = pd.read_excel(xls, 'Pruebas_BR') if 'Pruebas_BR' in xls.sheet_names else pd.DataFrame()
        df_s_br = pd.read_excel(xls, 'Servicios_BR') if 'Servicios_BR' in xls.sheet_names else pd.DataFrame()
        return df_p_usd, df_s_usd, df_config, df_p_cl, df_s_cl, df_p_br, df_s_br
    except: return None, None, None, None, None, None, None

data = cargar_datos()
if data[0] is None:
    st.error("⚠️ Error crítico: Falta 'precios.xlsx' en GitHub.")
    st.stop()
df_p_usd, df_s_usd, df_config, df_p_cl, df_s_cl, df_p_br, df_s_br = data

if not df_config.empty and 'Pais' in df_config.columns:
    TODOS_LOS_PAISES = sorted(df_config['Pais'].unique().tolist())
else:
    TODOS_LOS_PAISES = ["Chile", "Brasil"]

# --- 3. APIS ---
@st.cache_data(ttl=3600)
def obtener_indicadores():
    tasas = {"UF": 38000, "USD_CLP": 980, "USD_BRL": 5.8}
    try:
        r_cl = requests.get('https://mindicador.cl/api', timeout=5).json()
        tasas['UF'], tasas['USD_CLP'] = r_cl['uf']['valor'], r_cl['dolar']['valor']
        r_br = requests.get('https://open.er-api.com/v6/latest/USD', timeout=5).json()
        tasas['USD_BRL'] = r_br['rates']['BRL']
    except: pass
    return tasas
TASAS_DIA = obtener_indicadores()

# --- LÓGICA ---
def obtener_contexto_pais(pais):
    if pais == "Chile": return {"moneda": "UF", "df_p": df_p_cl, "df_s": df_s_cl, "tipo": "Local"}
    elif pais in ["Brasil", "Brazil"]: return {"moneda": "R$", "df_p": df_p_br, "df_s": df_s_br, "tipo": "Local"}
    else:
        fila = df_config[df_config['Pais'] == pais]
        nivel = fila.iloc[0]['Nivel'] if not fila.empty else "Medio"
        return {"moneda": "US$", "df_p": df_p_usd, "df_s": df_s_usd, "tipo": "Internacional", "nivel": nivel}

def determinar_empresa_facturadora(pais, items_carrito):
    if pais == "Brasil": return EMPRESAS["Brasil"]
    if pais in ["Perú", "Peru"]: return EMPRESAS["Peru"]
    if pais == "Chile":
        hay_pruebas = any(item['Ítem'] == 'Evaluación' for item in items_carrito)
        return EMPRESAS["Chile_Pruebas"] if hay_pruebas else EMPRESAS["Chile_Servicios"]
    return EMPRESAS["Latam"]

def calcular_impuestos(pais, subtotal, total_pruebas):
    if pais == "Chile": return "IVA (19% s/Pruebas)", total_pruebas * 0.19
    elif pais in ["Panamá", "Panama"]: return "ITBMS (7%)", subtotal * 0.07
    elif pais == "Honduras": return "Retención (11.11%)", subtotal * 0.1111
    return "", 0.0

# --- GENERADOR PDF (DISEÑO DIGITAL PREMIUM) ---
class PDF(FPDF):
    def __init__(self, titulo_doc, empresa_data):
        super().__init__()
        self.titulo_doc = titulo_doc
        self.empresa_data = empresa_data
        
    def header(self):
        # Logo
        if os.path.exists(LOGO_PATH):
            self.image(LOGO_PATH, 10, 10, 33) # Logo a la izquierda
        
        # Título "COTIZACIÓN" a la derecha
        self.set_font('Arial', 'B', 24)
        self.set_text_color(0, 51, 102) # Azul TalentPro
        self.cell(0, 15, self.titulo_doc, 0, 1, 'R')
        
        # Línea separadora azul gruesa
        self.set_draw_color(0, 51, 102)
        self.set_line_width(1)
        self.line(10, 30, 200, 30)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'TalentPro - Digital Assessment & Services', 0, 0, 'C')

def generar_pdf_pro(empresa_emisora, cliente, items, calculos, idioma, id_cot):
    t = TEXTOS[idioma]
    pdf = PDF(t['quote'], empresa_emisora)
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- 1. INFORMACIÓN DE EMPRESAS ---
    pdf.ln(10)
    
    # Columna Izq: Emisor (TalentPro)
    pdf.set_font("Arial", 'B', 10)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(95, 5, empresa_emisora['Nombre'], 0, 0)
    
    # Columna Der: Cliente
    pdf.set_text_color(100, 100, 100) # Gris
    pdf.cell(95, 5, f"{t['invoice_to']}", 0, 1)
    
    # Datos Emisor
    pdf.set_font("Arial", '', 9)
    pdf.set_text_color(50, 50, 50)
    y_start = pdf.get_y()
    pdf.cell(95, 5, empresa_emisora['ID'], 0, 1)
    pdf.multi_cell(90, 5, empresa_emisora['Dir'])
    pdf.cell(95, 5, empresa_emisora['Giro'], 0, 1)
    
    # Datos Cliente (Posicionamiento manual a la derecha)
    pdf.set_xy(105, y_start)
    pdf.set_font("Arial", 'B', 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(95, 5, cliente['empresa'], 0, 1)
    
    pdf.set_xy(105, pdf.get_y())
    pdf.set_font("Arial", '', 9)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(95, 5, f"{cliente['contacto']}", 0, 1)
    pdf.set_xy(105, pdf.get_y())
    pdf.cell(95, 5, f"{cliente['email']}", 0, 1)
    
    # Datos Fecha y ID
    pdf.set_xy(105, pdf.get_y() + 2)
    pdf.set_font("Arial", 'B', 9)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(95, 5, f"{t['date']}: {datetime.now().strftime('%d/%m/%Y')}  |  ID: {id_cot}", 0, 1)
    
    pdf.ln(15)
    
    # --- 2. TABLA DE PRODUCTOS ---
    # Encabezados
    pdf.set_fill_color(0, 51, 102) # Azul TalentPro
    pdf.set_text_color(255, 255, 255) # Blanco
    pdf.set_font("Arial", 'B', 9)
    pdf.set_draw_color(0, 51, 102)
    
    pdf.cell(110, 10, f"  {t['desc']}", 1, 0, 'L', 1)
    pdf.cell(20, 10, t['qty'], 1, 0, 'C', 1)
    pdf.cell(30, 10, t['unit'], 1, 0, 'R', 1)
    pdf.cell(30, 10, t['total'], 1, 1, 'R', 1)
    
    # Filas
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", '', 9)
    pdf.set_fill_color(245, 245, 245) # Gris muy claro alternado
    fill = False
    
    mon = items[0]['Moneda']
    
    for item in items:
        desc = str(item['Desc'])
        # Limpieza visual de cantidad
        qty_clean = str(item['Det']).split('(')[0].replace('x','').strip()
        if not qty_clean or not qty_clean[0].isdigit(): qty_clean = "1"
        
        # Celda descripción con ajuste automático
        pdf.cell(110, 8, f"  {desc}", 'LB', 0, 'L', fill)
        pdf.cell(20, 8, qty_clean, 'B', 0, 'C', fill)
        pdf.cell(30, 8, f"{item['Unit']:,.2f}", 'B', 0, 'R', fill)
        pdf.cell(30, 8, f"{item['Total']:,.2f}", 'RB', 1, 'R', fill)
        # fill = not fill # Si quieres alternar colores, descomenta esto
    
    pdf.ln(5)
    
    # --- 3. TOTALES (DISEÑO DERECHA) ---
    x_totales = 120
    w_labels = 35
    w_values = 35
    
    def fila_total(texto, valor, es_final=False):
        pdf.set_x(x_totales)
        
        if es_final:
            pdf.set_font("Arial", 'B', 11)
            pdf.set_fill_color(0, 51, 102) # Fondo Azul
            pdf.set_text_color(255, 255, 255) # Texto Blanco
            pdf.cell(w_labels, 10, f" {texto} ", 0, 0, 'R', 1)
            pdf.cell(w_values, 10, f"{mon} {valor:,.2f} ", 0, 1, 'R', 1)
        else:
            pdf.set_font("Arial", '', 10)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(w_labels, 7, texto, 0, 0, 'R')
            pdf.set_text_color(0, 0, 0)
            pdf.cell(w_values, 7, f"{mon} {valor:,.2f}", 0, 1, 'R')

    fila_total(t['subtotal'], calculos['subtotal'])
    if calculos['fee'] > 0: fila_total(t['fee'], calculos['fee'])
    if calculos['tax_val'] > 0: fila_total(calculos['tax_name'], calculos['tax_val'])
    if calculos['bank'] > 0: fila_total("Bank Fee", calculos['bank'])
    if calculos['desc'] > 0: fila_total(t['discount'], -calculos['desc'])
    
    pdf.ln(2)
    fila_total(t['grand_total'], calculos['total'], es_final=True)
    
    # --- 4. PIE DE PÁGINA Y VALIDEZ ---
    pdf.ln(15)
    pdf.set_text_color(100, 100, 100)
    pdf.set_font("Arial", '', 9)
    pdf.cell(0, 5, t['validity'], 0, 1, 'L')
    pdf.cell(0, 5, t['generated'], 0, 1, 'L')

    return pdf.output(dest='S').encode('latin-1')

# --- UI ---
if 'cotizaciones' not in st.session_state: st.session_state['cotizaciones'] = pd.DataFrame(columns=['id', 'fecha', 'empresa', 'pais', 'total', 'moneda', 'estado', 'vendedor'])
if 'carrito' not in st.session_state: st.session_state['carrito'] = []

def calcular_paa(cantidad, moneda_destino):
    if cantidad <= 2: base_usd = 1500
    elif cantidad <= 5: base_usd = 1200
    else: base_usd = 1100
    
    if moneda_destino == "US$": return base_usd, f"Tramo USD: ${base_usd}"
    elif moneda_destino == "UF": return (base_usd * TASAS_DIA['USD_CLP']) / TASAS_DIA['UF'], "(USD*Dolar)/UF"
    elif moneda_destino == "R$": return base_usd * TASAS_DIA['USD_BRL'], f"USD * {TASAS_DIA['USD_BRL']}"
    return 0.0, "Err"

def calc_excel(df, prod, cant, es_local):
    if df.empty: return 0.0
    fila = df[df['Producto'] == prod]
    if fila.empty: return 0.0
    tramos = [50, 100, 200, 300, 500, 1000, 'Infinito'] if es_local else [100, 200, 300, 500, 1000, 'Infinito']
    for t in tramos:
        lim = float('inf') if t == 'Infinito' else t
        if cant <= lim:
            try: return float(fila.iloc[0][t])
            except: 
                try: return float(fila.iloc[0][str(t)])
                except: return 0.0
    return 0.0

def cotizador():
    col_lang, col_tit = st.columns([1, 6])
    idioma = col_lang.selectbox("🌐", ["ES", "EN", "PT"])
    txt = TEXTOS[idioma]
    col_tit.title(txt['title'])

    # 1. PAIS
    c1, c2 = st.columns([1, 2])
    idx_cl = TODOS_LOS_PAISES.index("Chile") if "Chile" in TODOS_LOS_PAISES else 0
    pais_sel = c1.selectbox("🌎 País", TODOS_LOS_PAISES, index=idx_cl)
    
    ctx = obtener_contexto_pais(pais_sel)
    c2.info(f"Moneda: **{ctx['moneda']}** | Tipo: **{ctx['tipo']}** {f'({ctx.get('nivel','')})' if ctx['tipo']=='Internacional' else ''}")

    # 2. CLIENTE
    st.markdown("---")
    cc1, cc2, cc3, cc4 = st.columns(4)
    empresa = cc1.text_input(txt['client'])
    contacto = cc2.text_input("Contacto")
    email = cc3.text_input("Email")
    vendedor = cc4.selectbox("Ejecutivo", ["Comercial 1", "Comercial 2", "Gerencia"])

    # 3. ITEMS
    st.markdown("---")
    tp, ts = st.tabs(["🧩 Evaluaciones", "💼 Servicios"])
    
    with tp:
        cp1, cp2, cp3, cp4 = st.columns([3, 1, 1, 1])
        lst_p = ctx['df_p']['Producto'].unique().tolist() if not ctx['df_p'].empty else []
        if lst_p:
            sel_p = cp1.selectbox("Item", lst_p, key="p_sel")
            cant_p = cp2.number_input(txt['qty'], 1, 10000, 10, key="p_cant")
            es_loc = (ctx['tipo'] == 'Local')
            up = calc_excel(ctx['df_p'], sel_p, cant_p, es_loc)
            cp3.metric(txt['unit'], f"{ctx['moneda']} {up:,.2f}")
            if cp4.button(txt['add'], key="ap"):
                st.session_state['carrito'].append({"Ítem": "Evaluación", "Desc": sel_p, "Det": f"x{cant_p}", "Moneda": ctx['moneda'], "Unit": up, "Total": up*cant_p})
                st.rerun()

    with ts:
        cs1, cs2, cs3, cs4 = st.columns([3, 2, 1, 1])
        lst_s_xls = ctx['df_s']['Servicio'].unique().tolist() if not ctx['df_s'].empty else []
        lst_full = ["Certificación PAA (Transversal)"] + lst_s_xls
        
        if lst_full:
            sel_s = cs1.selectbox("Servicio", lst_full, key="s_sel")
            if sel_s == "Certificación PAA (Transversal)":
                c_rol, c_qty = cs2.columns([1, 30])
                c_rol.write("")
                cant_s = c_qty.number_input(txt['qty'], 1, 1000, 1, key="s_cant")
                us, _ = calcular_paa(cant_s, ctx['moneda'])
                det_txt = f"{cant_s} pers"
            else:
                c_rol, c_qty = cs2.columns(2)
                cols_serv = ctx['df_s'].columns.tolist()
                posibles_roles = ['Angelica', 'Senior', 'BM', 'BP']
                roles_validos = [r for r in posibles_roles if r in cols_serv]
                rol = c_rol.selectbox("Rol", roles_validos) if roles_validos else cols_serv[-1]
                cant_s = c_qty.number_input(txt['qty'], 1, 1000, 1)
                
                us = 0.0
                if ctx['tipo'] == "Internacional":
                    row = ctx['df_s'][(ctx['df_s']['Servicio']==sel_s) & (ctx['df_s']['Nivel']==ctx['nivel'])]
                else:
                    row = ctx['df_s'][ctx['df_s']['Servicio']==sel_s]
                if not row.empty: us = float(row.iloc[0][rol]) if rol in row.columns else 0.0
                det_txt = f"{rol} ({cant_s})"

            cs3.metric(txt['unit'], f"{ctx['moneda']} {us:,.2f}")
            if cs4.button(txt['add'], key="as"):
                st.session_state['carrito'].append({"Ítem": "Servicio", "Desc": sel_s, "Det": det_txt, "Moneda": ctx['moneda'], "Unit": us, "Total": us*cant_s})
                st.rerun()

     # 4. RESUMEN
    if st.session_state['carrito']:
        st.markdown("---")
        df_c = pd.DataFrame(st.session_state['carrito'])
        if len(df_c['Moneda'].unique()) > 1: st.error("Error: Monedas mezcladas.")
        else:
            mon = df_c['Moneda'].unique()[0]
            st.dataframe(df_c[['Desc', 'Det', 'Unit', 'Total']], use_container_width=True)
            
            subtotal = df_c['Total'].sum()
            tot_eval = df_c[df_c['Ítem']=='Evaluación']['Total'].sum()
            
            cL, cR = st.columns([3, 1])
            with cR:
                fee = st.checkbox(txt['fee'], value=False)
                bank = st.number_input("Bank Fee", 0.0, value=30.0 if mon=="US$" else 0.0)
                desc = st.number_input(txt['discount'], 0.0)
                
                val_fee = tot_eval * 0.10 if fee else 0.0
                tax_name, val_tax = calcular_impuestos(pais_sel, subtotal, tot_eval)
                final = subtotal + val_fee + val_tax + bank - desc
                
                st.markdown(f"""
                **{txt['subtotal']}:** {mon} {subtotal:,.2f}  
                **{txt['fee'] if val_fee > 0 else 'Fee'}:** {mon} {val_fee:,.2f}  
                **{tax_name}:** {mon} {val_tax:,.2f}  
                **Bank:** {mon} {bank:,.2f}  
                **Desc:** -{mon} {desc:,.2f}  
                ### {txt['grand_total']}: {mon} {final:,.2f}
                """)
                
                if st.button(txt['save'], type="primary"):
                    if not empresa: st.error("Error: Falta Empresa")
                    else:
                        nid = f"TP-{random.randint(1000,9999)}"
                        entidad = determinar_empresa_facturadora(pais_sel, st.session_state['carrito'])
                        calcs = {'subtotal':subtotal, 'fee':val_fee, 'tax_name':tax_name, 'tax_val':val_tax, 'bank':bank, 'desc':desc, 'total':final}
                        cli = {'empresa':empresa, 'contacto':contacto, 'email':email}
                        
                        # GENERAR PDF PRO
                        pdf_bytes = generar_pdf_pro(entidad, cli, st.session_state['carrito'], calcs, idioma, nid)
                        
                        b64 = base64.b64encode(pdf_bytes).decode('latin-1')
                        href = f'<a href="data:application/pdf;base64,{b64}" download="Cotizacion_{nid}.pdf" style="background-color:#003366;color:white;padding:10px 20px;text-decoration:none;border-radius:8px;font-weight:bold;">{txt["download"]}</a>'
                        st.markdown(href, unsafe_allow_html=True)
                        
                        st.session_state['cotizaciones'] = pd.concat([st.session_state['cotizaciones'], pd.DataFrame([{
                            'id': nid, 'fecha': datetime.now().strftime("%Y-%m-%d"), 'empresa': empresa, 'pais': pais_sel,
                            'total': final, 'moneda': mon, 'estado': 'Enviada', 'vendedor': vendedor
                        }])], ignore_index=True)
                        st.session_state['carrito'] = []
                        st.success("Cotización creada correctamente.")
            with cL:
                if st.button("🗑️"): st.session_state['carrito']=[]; st.rerun()

def dashboard():
    st.title("📊 Dashboard")
    df = st.session_state['cotizaciones']
    if df.empty: st.info("No data"); return
    c1, c2 = st.columns(2)
    c1.dataframe(df.groupby('moneda')['total'].sum())
    c2.metric("Total", len(df))

def finanzas():
    st.title("💰 Finanzas")
    df = st.session_state['cotizaciones']
    if df.empty: return
    ed = st.data_editor(df, disabled=["id"], hide_index=True)
    if not ed.equals(df): st.session_state['cotizaciones'] = ed

with st.sidebar:
    # Logo Sidebar
    if os.path.exists(LOGO_PATH): st.image(LOGO_PATH, width=150)
    op = st.radio("Menu", ["Cotizador", "Dashboard", "Finanzas"])

if op == "Cotizador": cotizador()
elif op == "Dashboard": dashboard()
elif op == "Finanzas": finanzas()
